name: mnist_pytorch_lightning_const
data:
  url: "https://s3-us-west-2.amazonaws.com/determined-ai-test-data/pytorch_mnist.tar.gz"
hyperparameters:
  global_batch_size: 64
  hidden_size: 64
  learning_rate: 0.001
searcher:
  name: single
  metric: val_loss
  max_length:
      batches: 937
  smaller_is_better: true
entrypoint: model_def:MNISTTrial
