name: imagenet_pytorch_dist
hyperparameters:
  global_batch_size: 1024 # 256 * 4 gpu slots
  data_location: /mnt/data
  arch: resnet18
  workers: 4
  lr: 0.1
  momentum: 0.9
  weight_decay: 1e-4
  evaluate: store_true
  pretrained: True
  dataset: imagenet
records_per_epoch: 50000
resources:
  slots_per_trial: 4
searcher:
  name: single
  metric: val_loss
  smaller_is_better: true
  max_length:
    epochs: 60
entrypoint: model_def:ImagenetTrial
# set to imagenet path
bind_mounts:
  - host_path: /mnt/data
    container_path: /mnt/data
environment:
  environment_variables:
    - DET_MASTER=192.168.201.75
    - http_proxy=http://172.28.6.17:3128
    - https_proxy=http://172.28.6.17:3128
    - ftp_proxy=http://172.28.6.17:3128
    - no_proxy=localhost,127.0.0.1,gl-hpe.local,10.111.135.214,192.168.201.75

